# https://raw.githubusercontent.com/dgraph-io/dgraph/master/contrib/config/docker/docker-compose.yml

version: '3.8'
services:
  man-go:
    container_name: man-go
    build: .
    ports:
      - "7777:7777"